language: go
go:
 - release
 - tip

env:
 - DATE=`date -u "+%F %T UTC"`

install:
 - go get github.com/axw/gocov/gocov
 - go get github.com/mattn/goveralls
 - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
 - go test -v ./...
 - $HOME/gopath/bin/goveralls -service=travis-ci

after_success:
 - echo $DATE
